name: Run Pytest

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest
    env:
      DB_USER: "postgres"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest

      - name: Failure Log
        if: failure()
        run: |
          echo "1つ前のstepが失敗しました"

      - name: Print DB_USER
        run: |
          echo "DB_USER -> ${DB_USER}"

      - name: Print secrets
        run: |
          echo "API_KEY -> ${{ secrets.API_KEY }}"

      - name: Get ime
        id: get_time
        run: |
          echo "time=$(date)" >> $GITHUB_OUTPUT

      - name: Print github output
        run: |
          echo "1つ前のstepの出力は${{ steps.get_time.outputs.time }}です"